# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sec2.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import constants_pb2 as constants__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sec2.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nsec2.proto\x1a\x0f\x63onstants.proto\"?\n\rS2SessionCmd0\x12\x17\n\x0f\x63lient_username\x18\x01 \x01(\x0c\x12\x15\n\rclient_pubkey\x18\x02 \x01(\x0c\"U\n\x0eS2SessionResp0\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x15\n\rdevice_pubkey\x18\x02 \x01(\x0c\x12\x13\n\x0b\x64\x65vice_salt\x18\x03 \x01(\x0c\"%\n\rS2SessionCmd1\x12\x14\n\x0c\x63lient_proof\x18\x01 \x01(\x0c\"U\n\x0eS2SessionResp1\x12\x17\n\x06status\x18\x01 \x01(\x0e\x32\x07.Status\x12\x14\n\x0c\x64\x65vice_proof\x18\x02 \x01(\x0c\x12\x14\n\x0c\x64\x65vice_nonce\x18\x03 \x01(\x0c\"\xb1\x01\n\x0bSec2Payload\x12\x19\n\x03msg\x18\x01 \x01(\x0e\x32\x0c.Sec2MsgType\x12\x1d\n\x03sc0\x18\x14 \x01(\x0b\x32\x0e.S2SessionCmd0H\x00\x12\x1e\n\x03sr0\x18\x15 \x01(\x0b\x32\x0f.S2SessionResp0H\x00\x12\x1d\n\x03sc1\x18\x16 \x01(\x0b\x32\x0e.S2SessionCmd1H\x00\x12\x1e\n\x03sr1\x18\x17 \x01(\x0b\x32\x0f.S2SessionResp1H\x00\x42\t\n\x07payload*o\n\x0bSec2MsgType\x12\x16\n\x12S2Session_Command0\x10\x00\x12\x17\n\x13S2Session_Response0\x10\x01\x12\x16\n\x12S2Session_Command1\x10\x02\x12\x17\n\x13S2Session_Response1\x10\x03\x62\x06proto3'
  ,
  dependencies=[constants__pb2.DESCRIPTOR,])

_SEC2MSGTYPE = _descriptor.EnumDescriptor(
  name='Sec2MsgType',
  full_name='Sec2MsgType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='S2Session_Command0', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2Session_Response0', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2Session_Command1', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='S2Session_Response1', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=489,
  serialized_end=600,
)
_sym_db.RegisterEnumDescriptor(_SEC2MSGTYPE)

Sec2MsgType = enum_type_wrapper.EnumTypeWrapper(_SEC2MSGTYPE)
S2Session_Command0 = 0
S2Session_Response0 = 1
S2Session_Command1 = 2
S2Session_Response1 = 3



_S2SESSIONCMD0 = _descriptor.Descriptor(
  name='S2SessionCmd0',
  full_name='S2SessionCmd0',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_username', full_name='S2SessionCmd0.client_username', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_pubkey', full_name='S2SessionCmd0.client_pubkey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=94,
)


_S2SESSIONRESP0 = _descriptor.Descriptor(
  name='S2SessionResp0',
  full_name='S2SessionResp0',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='S2SessionResp0.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_pubkey', full_name='S2SessionResp0.device_pubkey', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_salt', full_name='S2SessionResp0.device_salt', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=181,
)


_S2SESSIONCMD1 = _descriptor.Descriptor(
  name='S2SessionCmd1',
  full_name='S2SessionCmd1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_proof', full_name='S2SessionCmd1.client_proof', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=220,
)


_S2SESSIONRESP1 = _descriptor.Descriptor(
  name='S2SessionResp1',
  full_name='S2SessionResp1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='S2SessionResp1.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_proof', full_name='S2SessionResp1.device_proof', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_nonce', full_name='S2SessionResp1.device_nonce', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=307,
)


_SEC2PAYLOAD = _descriptor.Descriptor(
  name='Sec2Payload',
  full_name='Sec2Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Sec2Payload.msg', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sc0', full_name='Sec2Payload.sc0', index=1,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sr0', full_name='Sec2Payload.sr0', index=2,
      number=21, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sc1', full_name='Sec2Payload.sc1', index=3,
      number=22, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sr1', full_name='Sec2Payload.sr1', index=4,
      number=23, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='Sec2Payload.payload',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=310,
  serialized_end=487,
)

_S2SESSIONRESP0.fields_by_name['status'].enum_type = constants__pb2._STATUS
_S2SESSIONRESP1.fields_by_name['status'].enum_type = constants__pb2._STATUS
_SEC2PAYLOAD.fields_by_name['msg'].enum_type = _SEC2MSGTYPE
_SEC2PAYLOAD.fields_by_name['sc0'].message_type = _S2SESSIONCMD0
_SEC2PAYLOAD.fields_by_name['sr0'].message_type = _S2SESSIONRESP0
_SEC2PAYLOAD.fields_by_name['sc1'].message_type = _S2SESSIONCMD1
_SEC2PAYLOAD.fields_by_name['sr1'].message_type = _S2SESSIONRESP1
_SEC2PAYLOAD.oneofs_by_name['payload'].fields.append(
  _SEC2PAYLOAD.fields_by_name['sc0'])
_SEC2PAYLOAD.fields_by_name['sc0'].containing_oneof = _SEC2PAYLOAD.oneofs_by_name['payload']
_SEC2PAYLOAD.oneofs_by_name['payload'].fields.append(
  _SEC2PAYLOAD.fields_by_name['sr0'])
_SEC2PAYLOAD.fields_by_name['sr0'].containing_oneof = _SEC2PAYLOAD.oneofs_by_name['payload']
_SEC2PAYLOAD.oneofs_by_name['payload'].fields.append(
  _SEC2PAYLOAD.fields_by_name['sc1'])
_SEC2PAYLOAD.fields_by_name['sc1'].containing_oneof = _SEC2PAYLOAD.oneofs_by_name['payload']
_SEC2PAYLOAD.oneofs_by_name['payload'].fields.append(
  _SEC2PAYLOAD.fields_by_name['sr1'])
_SEC2PAYLOAD.fields_by_name['sr1'].containing_oneof = _SEC2PAYLOAD.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['S2SessionCmd0'] = _S2SESSIONCMD0
DESCRIPTOR.message_types_by_name['S2SessionResp0'] = _S2SESSIONRESP0
DESCRIPTOR.message_types_by_name['S2SessionCmd1'] = _S2SESSIONCMD1
DESCRIPTOR.message_types_by_name['S2SessionResp1'] = _S2SESSIONRESP1
DESCRIPTOR.message_types_by_name['Sec2Payload'] = _SEC2PAYLOAD
DESCRIPTOR.enum_types_by_name['Sec2MsgType'] = _SEC2MSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

S2SessionCmd0 = _reflection.GeneratedProtocolMessageType('S2SessionCmd0', (_message.Message,), {
  'DESCRIPTOR' : _S2SESSIONCMD0,
  '__module__' : 'sec2_pb2'
  # @@protoc_insertion_point(class_scope:S2SessionCmd0)
  })
_sym_db.RegisterMessage(S2SessionCmd0)

S2SessionResp0 = _reflection.GeneratedProtocolMessageType('S2SessionResp0', (_message.Message,), {
  'DESCRIPTOR' : _S2SESSIONRESP0,
  '__module__' : 'sec2_pb2'
  # @@protoc_insertion_point(class_scope:S2SessionResp0)
  })
_sym_db.RegisterMessage(S2SessionResp0)

S2SessionCmd1 = _reflection.GeneratedProtocolMessageType('S2SessionCmd1', (_message.Message,), {
  'DESCRIPTOR' : _S2SESSIONCMD1,
  '__module__' : 'sec2_pb2'
  # @@protoc_insertion_point(class_scope:S2SessionCmd1)
  })
_sym_db.RegisterMessage(S2SessionCmd1)

S2SessionResp1 = _reflection.GeneratedProtocolMessageType('S2SessionResp1', (_message.Message,), {
  'DESCRIPTOR' : _S2SESSIONRESP1,
  '__module__' : 'sec2_pb2'
  # @@protoc_insertion_point(class_scope:S2SessionResp1)
  })
_sym_db.RegisterMessage(S2SessionResp1)

Sec2Payload = _reflection.GeneratedProtocolMessageType('Sec2Payload', (_message.Message,), {
  'DESCRIPTOR' : _SEC2PAYLOAD,
  '__module__' : 'sec2_pb2'
  # @@protoc_insertion_point(class_scope:Sec2Payload)
  })
_sym_db.RegisterMessage(Sec2Payload)


# @@protoc_insertion_point(module_scope)
